<section class="quicklinks container">
    <p class="align-center">
        The Best 108 Maldives Resorts And Hotels, Maldives all inclusive holiday and Honeymoon Island Resorts
        <a href="javascript:;" class="quick"><i class="fa fa-angle-up"></i></a>
    </p>
    <ul>
        <li><a href="">Amilla Fushi</a></li>
        <li><a href="">Anantara Dhigu Resort And Spa</a></li>
        <li><a href="">Anantara Kihavah Villas</a></li>
        <li><a href="">Anantara Veli Maldives Resort</a></li>
        <li><a href="">Angsana Velavaru Resort And Spa</a></li>
        <li><a href="">Askani Villa - Hulhumale</a></li>
        <li><a href="">Athiri Inn - Ukulhas</a></li>
        <li><a href="">Atmosphere Kanifushi - Maldives</a></li>
        <li><a href="">Ayada Maldives</a></li>
        <li><a href="">Bandos Island Resort</a></li>
        <li><a href="">Banyan Tree Vabbinfaru</a></li>
        <li><a href="">Baros Maldives</a></li>
        <li><a href="">Bathala Island Resort</a></li>
        <li><a href="">Biyadhoo Island Resort</a></li>
        <li><a href="">Blancura Hotel</a></li>
        <li><a href="">Casa Mia Maldives At Mathiveri Island</a></li>
        <li><a href="">Centara Grand Island Resort And Spa Maldives</a></li>
        <li><a href="">Centara Ras Fushi Resort And Spa Maldives</a></li>
        <li><a href="">Cheval Blanc Randheli</a></li>
        <li><a href="">City Grand - Hulhumale</a></li>
        <li><a href="">Clear Sky Inn - Hulhumale</a></li>
        <li><a href="">Club Rannalhi - Adaaran</a></li>
        <li><a href="">Coco Palm Bodu Hithi</a></li>
        <li><a href="">Coco Palm Dhuni Kolhu</a></li>
        <li><a href="">Coco Privé Kuda Hithi Island</a></li>
        <li><a href="">Cocoa Island By Como, Maldives</a></li>
        <li><a href="">Conrad Maldives Rangali Island</a></li>
        <li><a href="">Constance Halaveli</a></li>
        <li><a href="">Constance Moofushi Maldives</a></li>
        <li><a href="">Dusit Thani Maldives</a></li>
        <li><a href="">Embudu Village</a></li>
        <li><a href="">Eriyadu Island Resort Maldives</a></li>
        <li><a href="">Filitheyo Island Resort</a></li>
        <li><a href="">Four Seasons At Landaa Giraavaru</a></li>
        <li><a href="">Four Seasons Resort At Kuda Huraa</a></li>
        <li><a href="">Fuana Inn - Hulhumale</a></li>

        <li><a href="">Amilla Fushi</a></li>
        <li><a href="">Anantara Dhigu Resort And Spa</a></li>
        <li><a href="">Anantara Kihavah Villas</a></li>
        <li><a href="">Anantara Veli Maldives Resort</a></li>
        <li><a href="">Angsana Velavaru Resort And Spa</a></li>
        <li><a href="">Askani Villa - Hulhumale</a></li>
        <li><a href="">Athiri Inn - Ukulhas</a></li>
        <li><a href="">Atmosphere Kanifushi - Maldives</a></li>
        <li><a href="">Ayada Maldives</a></li>
        <li><a href="">Bandos Island Resort</a></li>
        <li><a href="">Banyan Tree Vabbinfaru</a></li>
        <li><a href="">Baros Maldives</a></li>
        <li><a href="">Bathala Island Resort</a></li>
        <li><a href="">Biyadhoo Island Resort</a></li>
        <li><a href="">Blancura Hotel</a></li>
        <li><a href="">Casa Mia Maldives At Mathiveri Island</a></li>
        <li><a href="">Centara Grand Island Resort And Spa Maldives</a></li>
        <li><a href="">Centara Ras Fushi Resort And Spa Maldives</a></li>
        <li><a href="">Cheval Blanc Randheli</a></li>
        <li><a href="">City Grand - Hulhumale</a></li>
        <li><a href="">Clear Sky Inn - Hulhumale</a></li>
        <li><a href="">Club Rannalhi - Adaaran</a></li>
        <li><a href="">Coco Palm Bodu Hithi</a></li>
        <li><a href="">Coco Palm Dhuni Kolhu</a></li>
        <li><a href="">Coco Privé Kuda Hithi Island</a></li>
        <li><a href="">Cocoa Island By Como, Maldives</a></li>
        <li><a href="">Conrad Maldives Rangali Island</a></li>
        <li><a href="">Constance Halaveli</a></li>
        <li><a href="">Constance Moofushi Maldives</a></li>
        <li><a href="">Dusit Thani Maldives</a></li>
        <li><a href="">Embudu Village</a></li>
        <li><a href="">Eriyadu Island Resort Maldives</a></li>
        <li><a href="">Filitheyo Island Resort</a></li>
        <li><a href="">Four Seasons At Landaa Giraavaru</a></li>
        <li><a href="">Four Seasons Resort At Kuda Huraa</a></li>
        <li><a href="">Fuana Inn - Hulhumale</a></li>

        <li><a href="">Amilla Fushi</a></li>
        <li><a href="">Anantara Dhigu Resort And Spa</a></li>
        <li><a href="">Anantara Kihavah Villas</a></li>
        <li><a href="">Anantara Veli Maldives Resort</a></li>
        <li><a href="">Angsana Velavaru Resort And Spa</a></li>
        <li><a href="">Askani Villa - Hulhumale</a></li>
        <li><a href="">Athiri Inn - Ukulhas</a></li>
        <li><a href="">Atmosphere Kanifushi - Maldives</a></li>
        <li><a href="">Ayada Maldives</a></li>
        <li><a href="">Bandos Island Resort</a></li>
        <li><a href="">Banyan Tree Vabbinfaru</a></li>
        <li><a href="">Baros Maldives</a></li>
        <li><a href="">Bathala Island Resort</a></li>
        <li><a href="">Biyadhoo Island Resort</a></li>
        <li><a href="">Blancura Hotel</a></li>
        <li><a href="">Casa Mia Maldives At Mathiveri Island</a></li>
        <li><a href="">Centara Grand Island Resort And Spa Maldives</a></li>
        <li><a href="">Centara Ras Fushi Resort And Spa Maldives</a></li>
        <li><a href="">Cheval Blanc Randheli</a></li>
        <li><a href="">City Grand - Hulhumale</a></li>
        <li><a href="">Clear Sky Inn - Hulhumale</a></li>
        <li><a href="">Club Rannalhi - Adaaran</a></li>
        <li><a href="">Coco Palm Bodu Hithi</a></li>
        <li><a href="">Coco Palm Dhuni Kolhu</a></li>
        <li><a href="">Coco Privé Kuda Hithi Island</a></li>
        <li><a href="">Cocoa Island By Como, Maldives</a></li>
        <li><a href="">Conrad Maldives Rangali Island</a></li>
        <li><a href="">Constance Halaveli</a></li>
        <li><a href="">Constance Moofushi Maldives</a></li>
        <li><a href="">Dusit Thani Maldives</a></li>
        <li><a href="">Embudu Village</a></li>
        <li><a href="">Eriyadu Island Resort Maldives</a></li>
        <li><a href="">Filitheyo Island Resort</a></li>
        <li><a href="">Four Seasons At Landaa Giraavaru</a></li>
        <li><a href="">Four Seasons Resort At Kuda Huraa</a></li>
        <li><a href="">Fuana Inn - Hulhumale</a></li>
    </ul>
</section>